#define DEVICE_DESCRIPTION_TAG		"description"
#define DEVICE_SERIAL_NR_TAG		"serial"
#define DEVICE_LOCATION_ID_TAG		"locationId"
#define DEVICE_VENDOR_ID_TAG		"vendorId"
#define DEVICE_PRODUCT_ID_TAG		"productId"
#define DEVICE_INDEX_TAG			"index"

#define CONNECTION_BAUDRATE_TAG		"baudrate"
#define CONNECTION_DATABITS_TAG		"databits"
#define CONNECTION_STOPBITS_TAG		"stopbits"
#define CONNECTION_PARITY_TAG		"parity"

#define CONNECTION_PARITY_NONE		"none"
#define CONNECTION_PARITY_ODD		"odd"
#define CONNECTION_PARITY_EVEN		"even"